name: Deploy MuleSoft Application Demo
on:
  push:
    branches:
      - hotfix-v1.0.1
 
jobs:
  call-workflow:
    uses: IndrajithKatta/pipeline/.github/workflows/pipeline-hotfix.yml@main
    secrets: inherit

